### ISSUE TITLE
URL redirecting with error

### ISSUE THREAD

**Issue by tiankaima** [Asoul-au/Web#2]
To reproduce, open Github Page at https://asoul-au.github.io/Web/

click `search` and it returned a 404 error.

**Comment by tiankaima** [comment]
Configured the DNS record from `Godaddy`, now the `https://asoul-au.live/` page points at this Github Page...

The issue remains...

**Comment by odeinjul** [comment]
I didn't notice you set a domain, maybe I need to modify some files later.
By the way, this repo works well if only published at github.io.
See [https://odeinjul.github.io/Web/](https://odeinjul.github.io/Web/)

**Comment by tiankaima** [comment]
ow, noted

**Comment by tiankaima** [comment]
I should have noticed you in advance... Sorry for the inconvience

**Comment by tiankaima** [comment]
So I'm assuming the correct way to fix this is to change the depth  defined in  `404.html` from 1 -> 0 since the project is running at root?

**Comment by odeinjul** [comment]
Fixed.
